services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mqtt-docker/config:/mosquitto/config
      - ./mqtt-docker/data:/mosquitto/data
      - ./mqtt-docker/log:/mosquitto/log

  flask_mqtt_api:
    build: mqtt-docker/flask_mqtt
    container_name: flask_mqtt_api
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USER=<USER>
      - MQTT_PASSWORD=<PASSWORD>
    ports:
      - "8080:8080"
    volumes:
      - ./mqtt-docker/flask_mqtt/flask_logs:/app/logs
    restart: unless-stopped
  sia-receiver:
    build: ./ajax-sia
    container_name: sia-mqtt
    ports:
      - "3000:3000"
    volumes:
      - ./ajax-sia/logs:/app/logs
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USER=<USER>
      - MQTT_PASSWORD=<PASSWORD>
      - SIA_PORT=3000
      - SIA_ACCOUNT=AAA
      - SIA_PASSWORD=abcd
    depends_on:
      - mosquitto
    restart: always
  deye-to-mqtt:
    build: deye-mqtt
    container_name: deye-to-mqtt
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USER=<USER>
      - MQTT_PASSWORD=<PASSWORD>
    volumes:
      - ./deye-mqtt/logs:/app/logs
    restart: unless-stopped
